### ISSUE TITLE
Add compatibility for C-Bus Ceiling Sweep Fan Controller L5501RFCP

### ISSUE THREAD

**Issue by arrikhan** [Nick-Adams-AU/5500SHAC-Cbus2MQTT#2] opened 2021-03-04 02:32 UTC
Would it be easy to add in configurations for CBUS fan controller in a similar way to dimmers? Using cgateweb I configured Home Assistant as follows but I cannot get it to behave the same way using this integration. The logs on SHAC show i receive in the command but I’m not sure the script knows how to execute it (or if its ignoring it).

Below is my configuration in Home Assistant, when compared to a dimmer it is not much different, but because it is defined as a ‘fan’ is cannot use brightness topics in HA.

`fan:
  - platform: mqtt
    name: Master Bedroom Ceiling Fan (CBUS)
    state_topic: "cbus/read/254/56/42/state"
    command_topic: "cbus/write/254/56/42/ramp"
    speed_state_topic: "cbus/read/254/56/42/level"
    speed_command_topic: "cbus/write/254/56/42/ramp"
    payload_high_speed: "100"
    payload_medium_speed: "66"
    payload_low_speed: "33"
    speeds:
      - "off"
      - low
      - medium
      - high     `

**Comment by Nick-Adams-AU** [comment] 2021-03-04 02:40
Thanks for your question!

I don't have any fan controllers to try this out however I would have expected that it still uses a level (0 to 255) to set the fan speed. The script should handle it fine if the value is in that range (0-255).

Does the script in SHAC show any errors?

**Comment by arrikhan** [comment] 2021-03-04 02:51
Script shows no errors, I was just about to add the log data i forgot to add above. The difference here it is sending a percentage. Maybe cgateweb is translating that to a number between 0-255?

Mqtt2cbus 04.03.2021 13:48:25
* arg: 1
  * string: cbus/write/254/56/48/ramp
* arg: 2
  * string: 33

**Comment by arrikhan** [comment] 2021-03-04 02:59
Just used my CBUS trigger controls that sets a percentage in setup, actual payload is indeed between 0-255 (ie: low fan speed i just pressed a CBUS button for 33% sets fan to ‘86’ in SHAC.

**Comment by Nick-Adams-AU** [comment] 2021-03-04 03:00
Ok, so the fan should still operate when you use HA, but just slower. Is that what you are seeing? i.e. we need to map 0-100 to 0-255.

**Comment by Nick-Adams-AU** [comment] 2021-03-04 03:05
Try updating these lines:

````yaml
payload_high_speed: "255"
payload_medium_speed: "170"
payload_low_speed: "85"
````

**Comment by arrikhan** [comment] 2021-03-04 03:12
Have set as follows and no change to response;

`  - platform: mqtt
    name: Office Ceiling Fan (CBUS)
    state_topic: "cbus/read/254/56/48/state"
    command_topic: "cbus/write/254/56/48/ramp"
    speed_state_topic: "cbus/read/254/56/48/level"
    speed_command_topic: "cbus/write/254/56/48/ramp"
    payload_high_speed: "255"
    payload_medium_speed: "170"
    payload_low_speed: "86"
    speeds:
      - "off"
      - low
      - medium
      - high `

LOGS:

`Mqtt2cbus 04.03.2021 14:09:04
* string: MQTT connected - receive
Mqtt2cbus 04.03.2021 14:11:17
* arg: 1
  * string: cbus/write/254/56/48/ramp
* arg: 2
  * string: 86
Mqtt2cbus 04.03.2021 14:11:42
* arg: 1
  * string: created MQTT client
* arg: 2
  * userdata: 0xb6e3e388
Mqtt2cbus 04.03.2021 14:11:42
* string: MQTT connected - receive `

**Comment by Nick-Adams-AU** [comment] 2021-03-04 03:17
Can you try setting the fan speed using a CBus edlt or switch and see what values the object has in the 5500SHAC?

**Comment by arrikhan** [comment] 2021-03-04 03:23
I did that previously and confirmed the 0-255 value range in SHAC

**Comment by arrikhan** [comment] 2021-03-04 03:32
I looked through cgateweb code and it looks like it converts percentage to CBUS value (I’m no coder ... but the math in the following fits, ie: cbusramp = percentagevalue*255/100. So changing the ‘value’ to cbus values should work in theory but its not.

`            default:
              var ramp = message.split(",");
              var num = Math.round(parseInt(ramp[0])*255/100)
              if (!isNaN(num) && num < 256) { `

**Comment by Nick-Adams-AU** [comment] 2021-03-04 03:46
I don't think this is a 100/255 conversion issue because the 0-100 values are still valid input.

Can you try generating a MQTT packet (HA > Configurations > Integrations > MQTT > Configure) with the below details and let me know if either work:

Topic: cbus/write/254/56/48/ramp
Payload: 255

Topic: cbus/write/254/56/48/switch
Payload: ON

Also, does changing the fan value from a CBus eDLT or switch correctly push back to HA?

**Comment by arrikhan** [comment] 2021-03-04 04:22
SWITCH command worked (on and off)
RAMP command did not.

`Mqtt2cbus 04.03.2021 15:17:30
* arg: 1
  * string: cbus/write/254/56/48/switch
* arg: 2
  * string: ON
Mqtt2cbus 04.03.2021 15:17:40
* arg: 1
  * string: cbus/write/254/56/48/switch
* arg: 2
  * string: OFF
Mqtt2cbus 04.03.2021 15:17:56
* arg: 1
  * string: cbus/write/254/56/48/ramp
* arg: 2
  * string: 255 `

**Comment by arrikhan** [comment] 2021-03-04 04:30
> Also, does changing the fan value from a CBus eDLT or switch correctly push back to HA?

YES!

**Comment by Nick-Adams-AU** [comment] 2021-03-04 04:39
> SWITCH command worked (on and off)
> RAMP command did not.

Hrmm...this is a doosey! These both use the same function to set the value.

There's nothing in the error log? When you set the value using the RAMP command, does it correctly update in the object page or is their no change?

**Comment by arrikhan** [comment] 2021-03-04 04:48
Ok, I’ve not been observing the error log. Sorry .. not familiar with the SHAC interface 

This is explicitly on ramp command

`Mqtt2cbus 04.03.2021 15:45:50
Resident script:74: attempt to call global 'round' (a nil value)
stack traceback:
 Resident script:74: in function <Resident script:27>
 [C]: in function 'loop_forever' `

**Comment by Nick-Adams-AU** [comment] 2021-03-04 05:03
> Ok, I’ve not been observing the error log. Sorry .. not familiar with the SHAC interface

That's cool. It's clunky at best!

> Mqtt2cbus 04.03.2021 15:45:50 Resident script:74: attempt to call global 'round' (a nil value) stack traceback: Resident script:74: in function <Resident script:27> [C]: in function 'loop_forever' 

Can you check the 5500SHAC firmware version? Click the "System" icon on the main page and then "System" and "Upgrade firmware". It should show the firmware version. You want to be on 1.6.0. If you aren't, you should update.

Secondly, you can try updating line 74 of the Mqtt2cbus script:

````yaml
num = round(ramp[1])
````
...to this:
````yaml
num = math.floor(ramp[1] + 0.5)
````

**Comment by Nick-Adams-AU** [comment] 2021-03-04 05:08
This is my fault! I have a user function that isn't included in the source code. Let me update it now.

So sorry for the run around. Give me 5.

**Comment by Nick-Adams-AU** [comment] 2021-03-04 05:11
Well that's embarrassing. I have committed the function change. You'll just need to update the `mqtt2cbus` resident script.

I owe you a beer!

https://github.com/Nick-Adams-AU/5500SHAC-Cbus2MQTT/commit/386a5092d2d5c606ee6ac61573467ff9e5b23ea2

**Comment by arrikhan** [comment] 2021-03-04 05:19
So i pasted in the new script (deleted the old one). Disabled/enabled it, watched it connect to broker.

Error is the same unfortunately.

**Comment by Nick-Adams-AU** [comment] 2021-03-04 05:38
Did you want to give this a go please:

> Secondly, you can try updating line 74 of the Mqtt2cbus script:
> 
> ```yaml
> num = round(ramp[1])
> ```
> 
> ...to this:
> 
> ```yaml
> num = math.floor(ramp[1] + 0.5)
> ```

**Comment by arrikhan** [comment] 2021-03-04 05:48
That’s got it.

I tested it on an entry with percentage values as well as CBUS values. It’s passing the raw number through and applying it so one fan is at “33” and one at “86”, being the one I’ve been testing with. I can change all the fans to CBUS values no probs.

Thanks !!! Nice Work!

**Comment by Nick-Adams-AU** [comment] 2021-03-04 05:50
I'm so sorry for the bug but glad you got it working!

**Comment by Nick-Adams-AU** [comment] 2021-03-04 05:50
Did you mind posting your final HA yaml so I can update the documentation?

**Comment by arrikhan** [comment] 2021-03-04 05:51
There are some teething issues;

New errors

Library cbuslogic:0: All arguments (net, app, group, val, ramprate) are required and must be non-nil
stack traceback:
 [C]: in function 'error'
 Library cbuslogic: in function 'SetCBusLevel'
 Resident script:71: in function <Resident script:27>
 [C]: in function 'loop_forever'

**Comment by arrikhan** [comment] 2021-03-04 05:52
I will do more testing.

**Comment by arrikhan** [comment] 2021-03-04 05:55
Ok it seems to get tied up when i hit “OFF” and then becomes unresponsive for a mintute, throws that error. Might be because I have coded “OFF” in my HA code which I haven’t seen in other examples today. I will remove the “OFF” from HA and see if that fixes it.

**Comment by Nick-Adams-AU** [comment] 2021-03-04 05:57
For testing, I'd try generating MQTT packets first and once everything is confirmed as working, move to the HA configuration. It can be easy to chain multiple issues together and make it hard to find!

**Comment by arrikhan** [comment] 2021-03-04 06:10
So the “switch off” sequence works using ./././switch “OFF” in MQTT config but I think I am missing a payload option that triggers it to use switch statement instead of ramp. I struggle to understand the details of how each line parses an outcome but I will slowly add the lines missing in my config from [https://www.home-assistant.io/integrations/fan.mqtt/](url)

**Comment by Nick-Adams-AU** [comment] 2021-03-04 06:27
So there is some difference between the HA data model and CBus.

CBus says that a value of 0 is "off" and anything > 0 is "on". There isn't actually a separate value for on or off like in HA.

HA can have a light or fan switched "on" (SWITCH) but at 0% (RAMP). Conversely, HA can have a light or fan at 100% but switched "off".

The scripts translates the "switch off" to a CBus value of 0. Hope that helps but let me know how you go.

**Comment by arrikhan** [comment] 2021-03-04 06:33
When I set payload_off: “0”, it successfully turns off fan but the state being set doesn’t get recognised by HA as OFF
When I set payload_off” “OFF” it doesn’t turn off the fan and throws that other error. I get the same when I don’t add this line at all.
When I remove payload_off altogether (which is where I started), it behaves as if I set it to “OFF”

My fan attributes are; 
`  - platform: mqtt
    name: Office Ceiling Fan (CBUS)
    state_topic: "cbus/read/254/56/48/state"
    command_topic: "cbus/write/254/56/48/ramp"
    speed_state_topic: "cbus/read/254/56/48/level"
    speed_command_topic: "cbus/write/254/56/48/ramp"
    payload_off: "OFF" <— this is the line I am playing with
    payload_high_speed: "255"
    payload_medium_speed: "170"
    payload_low_speed: "86"
    speeds:
      - "off"
      - low
      - medium
      - high `

**Comment by ZEi20T** [comment] 2022-04-15 02:09
Sorry to bump this, been playing with the fan today and managed to get it working with this config and "custom:fan-percent-button-row" from HACS.

it functions with percentage, and the pre-sets in the button card work well!

![image](https://user-images.githubusercontent.com/67130552/163506678-4d3cfdf5-0298-419f-bbca-71ca39ed7c9c.png)

  - platform: mqtt
    name: Alfresco Fan
    state_topic: "cbus/read/254/56/17/state"
    command_topic: "cbus/write/254/56/17/switch"
    percentage_state_topic: "cbus/read/254/56/17/level"
    percentage_command_topic: "cbus/write/254/56/17/ramp"
    speed_range_max: 255
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: true

EDIT: left out speed_range_max: 255

**Comment by Nick-Adams-AU** [comment] 2022-04-15 09:44
Thanks for the update! I'll add it to the documentation for future reference.

**Closed as completed by Nick-Adams-AU** 2022-04-15 09:44 UTC
